FROM eclipse-temurin:17-jre

# ca-certificates-java 설치 및 Java cacerts 동기화
RUN apt-get update && \
  apt-get install -y --no-install-recommends ca-certificates-java && \
  update-ca-certificates -f && \
  # 시스템 cacerts를 Java로 복사
  cp /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts && \
  rm -rf /var/lib/apt/lists/*

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=local", "app.jar"]

# docker image build 명령어 (이미지 빌드, latest 태그 추가)
# docker build -f Dockerfile-local -t leehh0221/eume-backend:latest .

# docker image push 명령어 (도커 허브에 이미지 업로드)
# docker push leehh0221/eume-backend:latest
